# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a0a7384138a8edfbac97d5b814d2eab74b6a0ec2372b24050294f38223f0561386c34907c271270b410666d91d440df584010e7825155a7aaf248fc5c802e1d

test:
  secret_key_base: 4742a40dcfb9451880646827f475431f3a6807886ed49274e7663a3199491acf7ebc7aade00feb91b2df4707e1c19905f7161e9c19304782fade1e5f09f7c2bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
